#!/usr/bin/python

# taskwarrior-hledger-add-hook
# launch hledger add on completion of transaction-related tasks

# this is psudo-code, obviously..

# define transaction_task trigger (default = +txn)
# define hledger --datafile override (default = '')

# if completed_task
#    continue
#    else exit
# if transaction_task
#    continue
#    else exit

# build hledger add command

# payee
# omit first word of description (verb, eg. "pay", "buy", "deposit", etc.)
# identify "noun" (upper-cased word(s) following verb) becomes payee
# words following noun become comment
# example:
# pay Koodo Mobile cel phone bill
# becomes:
# 'Koodo Mobile  ;cel phone bill' (notice two spaces followed by semi-colon)
# if no upper-cased word(s) found then everything after verb (desc.startswith:word) is payee
# example:
# pay koodo mobile cel phone bill
# becomes:
# 'koodo mobile cel phone bill'

# Account1
# if exist uda.account.any: then account:value = Account1 
# else if has priject.any: then project:value = Account1
# else Account1 = nul

# Amount1
# if exist uda.amount.any: then amount:value = Amount1
# else Amount1 = nul

# build hledger add argument string, example:
# hledger add today 'Koodo Mobile  ;cel phone bill' telcom

# issue hledger add command
# if hledger add completes (modifies hledger --datafile) exit
# else abort task completion
