#!/usr/bin/env python3

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
on-modify_hledger-add.py — Taskwarrior on-modify hook
Launches hledger add interactively when a transaction-tagged task is completed.

Trigger: pending → completed, AND task has a trigger tag OR description starts
         with a trigger verb.

Install: ~/.task/hooks/on-modify_hledger-add.py
Config:  ~/.task/config/hledger-add.rc  (include in .taskrc)
Version: 0.1.0
"""

import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

CONFIG_FILE = Path.home() / '.task' / 'config' / 'hledger-add.rc'
VERSION = '0.1.0'


# ============================================================================
# Config
# ============================================================================

def load_config() -> dict:
    cfg = {
        'journal':       '',
        'trigger_tags':  'txn,acct',
        'trigger_verbs': 'pay,buy',
        'amount_uda':    'amt',
    }
    if not CONFIG_FILE.exists():
        return cfg
    with CONFIG_FILE.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            k, _, v = line.partition('=')
            k = k.strip()
            v = v.split('#')[0].strip()
            if k in cfg and v:
                cfg[k] = v
    return cfg


# ============================================================================
# Trigger detection
# ============================================================================

def is_triggered(task: dict, cfg: dict) -> bool:
    tags = set(task.get('tags', []))
    trigger_tags = {t.strip() for t in cfg['trigger_tags'].split(',') if t.strip()}
    if tags & trigger_tags:
        return True
    desc = task.get('description', '')
    words = desc.split()
    first_word = words[0].lower() if words else ''
    trigger_verbs = {v.strip().lower() for v in cfg['trigger_verbs'].split(',') if v.strip()}
    if first_word in trigger_verbs:
        return True
    return bool(project_to_account(task.get('project', '')))


# ============================================================================
# Payee / comment parsing
# ============================================================================

def parse_payee(task: dict, trigger_verbs: set) -> tuple:
    """Return (payee, comment).

    Strategy 1: consecutive capitalised word(s) after verb → payee; rest → comment
    Strategy 2: first capitalised tag → payee; '' → comment
    Strategy 3: all words after verb (or full description) → payee; '' → comment
    """
    desc = task.get('description', '').strip()
    words = desc.split()

    rest = words
    if words and words[0].lower() in trigger_verbs:
        rest = words[1:]

    # Strategy 1: leading consecutive capitalised words
    if rest:
        payee_words = []
        i = 0
        while i < len(rest) and rest[i][0].isupper():
            payee_words.append(rest[i])
            i += 1
        if payee_words:
            comment_words = rest[i:]
            return ' '.join(payee_words), ' '.join(comment_words)

    # Strategy 2: first capitalised tag
    for tag in task.get('tags', []):
        if tag and tag[0].isupper():
            return tag, ''

    # Strategy 3: everything after verb
    if rest:
        return ' '.join(rest), ''

    return desc, ''


# ============================================================================
# Project → account mapping
# ============================================================================

# Map abbreviated/full TW project top-level to canonical hledger account type.
# exp.auto.insurance → expenses:auto:insurance
# ass.checking       → assets:checking
# home.reno          → None (not a ledger account type)
_ACCOUNT_PREFIXES = {
    'ass':         'assets',
    'asset':       'assets',
    'assets':      'assets',
    'lia':         'liabilities',
    'liab':        'liabilities',
    'liability':   'liabilities',
    'liabilities': 'liabilities',
    'exp':         'expenses',
    'expense':     'expenses',
    'expenses':    'expenses',
    'inc':         'income',
    'income':      'income',
    'rev':         'revenue',
    'revenue':     'revenue',
    'equ':         'equity',
    'equity':      'equity',
}


def project_to_account(project: str) -> str:
    """Return hledger account string if project top-level is a ledger type, else ''."""
    if not project:
        return ''
    parts = project.split('.')
    full = _ACCOUNT_PREFIXES.get(parts[0].lower(), '')
    if not full:
        return ''
    return ':'.join([full] + parts[1:])


# ============================================================================
# Journal stat
# ============================================================================

def journal_path(journal: str) -> Path:
    if journal:
        return Path(journal).expanduser()
    ledger_env = os.environ.get('LEDGER_FILE', '')
    if ledger_env:
        return Path(ledger_env).expanduser()
    return Path.home() / '.hledger.journal'


def get_journal_stat(journal: str) -> tuple:
    try:
        st = journal_path(journal).stat()
        return st.st_mtime, st.st_size
    except OSError:
        return 0.0, 0


# ============================================================================
# hledger interaction
# ============================================================================

def run_hledger_add(date: str, description: str, journal: str,
                    account: str = '', amount: str = '') -> int:
    cmd = ['hledger']
    if journal:
        cmd += ['-f', journal]
    cmd += ['add', date, description]
    if account:
        cmd.append(account)
        if amount:
            cmd.append(amount)

    try:
        tty = open('/dev/tty', 'r+b', buffering=0)
        proc = subprocess.run(cmd, stdin=tty, stdout=tty, stderr=tty)
        tty.close()
        return proc.returncode
    except OSError as e:
        print(f'[hledger-add] ERROR: could not open /dev/tty: {e}', file=sys.stderr)
        return 1


# ============================================================================
# Main
# ============================================================================

def main() -> int:
    data = sys.stdin.read().strip()
    lines = data.split('\n') if data else []
    if len(lines) < 2:
        if lines and lines[0]:
            print(lines[0])
        return 0

    original = json.loads(lines[0])
    modified = json.loads(lines[1])

    # Only trigger on pending → completed
    if original.get('status') != 'pending' or modified.get('status') != 'completed':
        print(json.dumps(modified))
        return 0

    cfg = load_config()

    if not is_triggered(modified, cfg):
        print(json.dumps(modified))
        return 0

    trigger_verbs = {v.strip().lower() for v in cfg['trigger_verbs'].split(',') if v.strip()}
    payee, comment = parse_payee(modified, trigger_verbs)

    # Date: task end date if available, else today
    end_raw = modified.get('end', '')
    if end_raw:
        try:
            date = datetime.strptime(end_raw[:8], '%Y%m%d').strftime('%Y-%m-%d')
        except ValueError:
            date = datetime.now().strftime('%Y-%m-%d')
    else:
        date = datetime.now().strftime('%Y-%m-%d')

    # Amount from UDA (optional)
    amount_uda = cfg.get('amount_uda', '')
    amount = modified.get(amount_uda, '').strip() if amount_uda else ''

    # hledger tags from TW metadata
    # project.home.reno → 'project: home.reno'
    # priority H        → 'pri: H'
    # +tag              → 'tag:'
    # Excluded: trigger_tags (txn, acct — already implicit), meta tags, and the payee tag
    meta_tags = {'test'}   # testing/workflow tags that shouldn't appear in the ledger
    trigger_tag_set = {t.strip() for t in cfg['trigger_tags'].split(',') if t.strip()} | meta_tags
    payee_lower = payee.lower()

    hledger_tags = []
    project = modified.get('project', '')
    if project:
        hledger_tags.append(f'project: {project}')
    priority = modified.get('priority', '')
    if priority:
        hledger_tags.append(f'pri: {priority}')
    for tag in modified.get('tags', []):
        if tag and tag not in trigger_tag_set and tag.lower() != payee_lower:
            hledger_tags.append(f'{tag}:')

    # Annotations — skip meta annotations added by hooks
    skip_prefixes = ('note:', 'ledger:', 'nb:')
    ann_texts = [
        a.get('description', '')
        for a in modified.get('annotations', [])
        if a.get('description') and not any(
            a['description'].startswith(p) for p in skip_prefixes
        )
    ]

    # Derive hledger account from project if top-level is a ledger account type
    # exp.auto.insurance → expenses:auto:insurance  (enables amount pre-fill)
    account = project_to_account(project)

    # Build hledger description argument (single line)
    # Format: 'Payee  ;human text  [amount if no account]  tag1:, tag2: value  | ann1 | ann2'
    # When account is derived, amount goes as positional arg instead of in comment
    comment_amount = '' if account else amount
    human_text = ' '.join(filter(None, [comment, comment_amount]))
    tags_text  = ', '.join(hledger_tags)
    ann_text   = ' | '.join(ann_texts)
    comment_text = '  '.join(filter(None, [human_text, tags_text, ann_text]))
    hledger_desc = payee + ('  ;' + comment_text if comment_text else '')

    journal = cfg.get('journal', '')
    mtime_before, size_before = get_journal_stat(journal)

    # Prompt
    detail_parts = [comment, amount]
    if account:
        detail_parts.append(f'{account}')
    detail = ' | '.join(filter(None, detail_parts))
    print(f'\n[hledger-add] {payee} — {date}' + (f'  ({detail})' if detail else ''), file=sys.stderr)

    run_hledger_add(date, hledger_desc, journal, account, amount)

    mtime_after, size_after = get_journal_stat(journal)
    recorded = (mtime_after > mtime_before and size_after > size_before)

    if recorded:
        ann = {
            'entry': datetime.utcnow().strftime('%Y%m%dT%H%M%SZ'),
            'description': f'ledger: {payee} {date}',
        }
        modified.setdefault('annotations', []).append(ann)
        print(f'[hledger-add] recorded: {payee} {date}', file=sys.stderr)
    else:
        print('[hledger-add] transaction not recorded — add to ledger manually', file=sys.stderr)

    print(json.dumps(modified))
    return 0


if __name__ == '__main__':
    sys.exit(main())
