#!/bin/python
import datetime
from tasklib.task import TaskWarrior, Task

# taskwarrior-hledger-add-hook
# launch hledger add on completion of transaction-related tasks

# this is psudo-code, obviously..

# define transaction_task trigger (default = +txn)
TRANSACTION_TAG = "txn"

# define hledger --file override (default = none)
JOURNAL_FILE = ''

# if is transaction_task
task = Task.from_input()
if task._original_data['status'] is 'pending' and task['status'] is 'completed' and task['tag'] contains TRANSACTION_TAG:




# read target journal file
#    test writable
#        else exit with error message
#    read modified time
#    read file size

# build hledger add command, space delimited
# hledger add [-f FILE] <date[code]> <payee[comment]> 
# comment starts with two spaces and a semicolon
# values with spaces need to be surrounded with apostrophes ('Payee Name  ;comment')
# values may be ommitted, but '' required to maintain sequence

# Date
# easiest thing is to use "today", and if another date is desired, it's easy to change interactively
# the format allows date to be followed by an arbitrary code in parenthesis (we can ignore that for now)

# Payee
# omit first word of description (verb, eg. "pay", "buy", "deposit", etc.)
# identify "noun" (upper-cased word(s) following verb) becomes payee
# words following noun become comment
# example:
# pay Koodo Mobile cel phone bill
# becomes:
# 'Koodo Mobile  ;cel phone bill' (notice two spaces followed by semi-colon)
# if no upper-cased word(s) found then everything after verb (desc.startswith:word) is payee
# example:
# pay koodo mobile cel phone bill
# becomes:
# 'koodo mobile cel phone bill'

# build hledger add argument string, example:
# hledger add --file=myfile.journal today 'Koodo Mobile  ;cel phone bill'

# issue hledger add command

# test for hledger non-zero exit
# else echo error_message "journal entry failed! 
sys.exit(1)

# test is_journal_added_to
# if journal_mod_time > original_journal_mod_time
# and journal_file_size > original_journal_file_size
# echo success_message
# exit

# else echo error_message "journal entry failed! 
sys.exit(1)
